- name: Create target directory
  file:
    path: "{{ logstash_remote_dest }}/src/"
    state: directory
    owner: user
    group: user
    mode: '766'

- name: Send logstash binary
  copy:
    src: "/home/dmitrii/Projects/spring-boot-sample/ops/artifactory/{{ logstash_name }}.tar.gz"
    dest: "{{ logstash_remote_dest }}/src/{{ logstash_name }}.tar.gz"
    owner: user
    group: user
    mode: '766'

- name: Unpack logstash binary
  unarchive:
    src: "{{ logstash_remote_dest }}/src/{{ logstash_name }}.tar.gz"
    dest: "{{ logstash_remote_dest }}"
    creates: "{{ logstash_remote_dest }}/{{ logstash_name }}"
    owner: user
    group: user
    mode: '766'
    remote_src: yes

- name: Set LS_JAVA_HOME
  become: yes
  lineinfile:
    dest: /etc/environment
    state: present
    regexp: '^LS_JAVA_HOME'
    line: 'LS_JAVA_HOME=/usr/lib/jvm/jdk-14.0.2'

- name: Set LS_HOME
  become: yes
  lineinfile:
    dest: /etc/environment
    state: present
    regexp: '^LS_HOME'
    line: 'LS_HOME={{ logstash_remote_dest }}/{{ logstash_name }}'

- name: Send logstash configurations
  template:
    src: "logstash/logstash.yml.j2"
    dest: "{{ logstash_remote_dest }}/{{ logstash_name }}/config/logstash.yml"
    owner: user
    group: user
    mode: '775'

- name: Send logstash pipeline configurations
  template:
    src: "logstash/pipelines.yml.j2"
    dest: "{{ logstash_remote_dest }}/{{ logstash_name }}/config/pipelines.yml"
    owner: user
    group: user
    mode: '775'

- name: Send logstash beats pipeline configurations
  template:
    src: "logstash/beats_pipeline.conf.j2"
    dest: "{{ logstash_remote_dest }}/{{ logstash_name }}/config/beats_pipeline.conf"
    owner: user
    group: user
    mode: '775'

- name: Add logstash service config
  template:
    src: "logstash/logstash.service.j2"
    dest: "/etc/systemd/system/logstash.service"

- name: Start logstash service
  service:
    enabled: true
    daemon_reload: yes
    name: "logstash"
    state: started