---
- name: create kafka system group
  group:
    name: kafka
    system: true
    state: present

- name: create kafka system user
  user:
    name: "{{ kafka_user }}"
    system: true
    shell: "/usr/sbin/nologin"
    group: kafka
    home: "{{ kafka_home }}"

- name: download java binary to local folder
  become: false
  get_url:
    url: "{{ get_java_url }}"
    dest: "/tmp/jdk-18.tar.gz"
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  delegate_to: localhost
  check_mode: false
  when: "{{ install }}"

- name: unpack kafka binaries
  become: false
  unarchive:
    src: "/tmp/jdk-18.tar.gz"
    dest: "/tmp"
  delegate_to: localhost
  check_mode: false
  register: unpack_bin
  when: "{{ install }}"

- name: propagate kafka binaries
  copy:
    src: "/tmp/jdk-18"
    dest: "{{ java_home }}"
    group: kafka
    owner: kafka
    mode: 0744
  when: "{{ install }}"

- name: Set JAVA_HOME
  become: yes
  lineinfile:
    dest: /etc/environment
    state: present
    regexp: '^JAVA_HOME'
    line: 'JAVA_HOME={{ java_home }}/jdk-18'
