---
- name: deploy application
  hosts: observable_host
  vars_files:
    - group_vars/otus_metrics.yml
  remote_user: irina
  become: yes
#  vars_files:
#    - vault.yml
  roles:
    - role: common
    - role: nginx-deb
    - role: app-otus
