version: '2'
services:
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    restart: always
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: {{ kafdrop_kafka_servers }}
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_SERVLET_CONTEXTPATH: "/"
