version: '2'
services:
  zookeeper:
    restart: always
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_SERVER_ID: {{ zookeeper_server_id }}
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SERVERS: {{ zookeeper_servers }}
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: {{ kafka_adv_listener_external }}
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
